apiVersion: v1
kind: Service
metadata:
  name: sample-metrics-app
  namespace: fivepercent-observability
  labels:
    app.kubernetes.io/name: sample-metrics-app
    app.kubernetes.io/part-of: fivepercent-observability-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sample-metrics-app
  ports:
    - name: http
      port: 80
      targetPort: http
