apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sample-metrics-app
  namespace: fivepercent-observability
  labels:
    app.kubernetes.io/name: sample-metrics-app
    app.kubernetes.io/part-of: fivepercent-observability-lab
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-metrics-app
  namespaceSelector:
    matchNames:
      - fivepercent-observability
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
